# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fastapi-ingress
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: api.local
#       http:
#         paths:#
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: fastapi
#                 port:#
#                   number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: / ## removed
spec:
  ingressClassName: nginx ## added
  rules:
    # - host: api.local ## removed
    -  http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  number: 80
