# Workflow Name
name: "deploy-app"

# Workflow Triggers
on:
  push:
    branches:
      - main

# Environment Variables
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER: ${{ vars.EKS_CLUSTER }}
  ECR_REPO: ${{ vars.ECR_REPO }}
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


# Define Jobs
jobs:
  BuildImageAndPush:
    name: "BuildImageAndPush to EKS"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt    
      - name: Dependency vulnerability scan
        run: |
          pip install pip-audit
          pip-audit

      - name: Run tests
        run: |
          echo "DATABASE_URL=sqlite:///./test.db" >> $GITHUB_ENV
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python -m pytest tests/
      - name: Build and Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.ECR_REPO}}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./
      
  DeployToEKS:
    needs: BuildImageAndPush
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Kubernetes config
        id: getconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} 
      - name: Login to ECR
        run: |
          kubectl get secret regcred || \
          kubectl create secret docker-registry regcred \
            --docker-server=${{ secrets.REGISTRY }} \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password)


      # - name: Deploy temp postgres
      #   run: |
      #     helm install db helm/postgres

      - name: Deploy with Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.EKS_CLUSTER }}
          chart-path: helm/appcharts
          namespace: default
          values: appimage=${{ secrets.REGISTRY }}/${{ env.ECR_REPO }},apptag=${{ github.run_number }}
          name: webapp
      - name: Create monitoring namespace
        run: kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy monitoring stack
        run: |

          kubectl apply -f helm/grafana-configmap.yaml         
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

          helm upgrade --install kube-prom prometheus-community/kube-prometheus-stack \
            -n monitoring \
            --wait \
            --timeout 15m \
            -f helm/grafana-values.yaml
          kubectl apply -f helm/service-monitor.yaml
      - name: Get Pods
        run: kubectl get pods -A
      - name: Get Service
        run: kubectl get svc 
      - name: Get Grafana password
        run: kubectl --namespace monitoring get secrets kube-prom-grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo  
      - name: Get IP of Network Load balancer
        run: |
          aws elbv2 describe-load-balancers \
            --query "LoadBalancers[?contains(LoadBalancerArn, 'net')].LoadBalancerArn" \
            --output text | tr '\t' '\n' | while read arn; do
              aws elbv2 describe-tags \
                --resource-arns "$arn" \
                --query "TagDescriptions[0].Tags[?Key=='kubernetes.io/service-name'].Value" \
                --output text | grep ingress && \
              aws elbv2 describe-load-balancers \
                --load-balancer-arns "$arn" \
                --query 'LoadBalancers[0].DNSName' \
                --output text
            done | xargs -n1 getent hosts | awk '{print $1}'
